language: "zh"

pipeline:
  - name: "MitieNLP"
    model: "data/total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
    dictionary_path: "user_dict.txt"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "RegexFeaturizer"
  - name: "MitieFeaturizer"
  - name: "SklearnIntentClassifier"

# 若训练数据中使用了查找表，那么在pipeline中需要有 DIETClassifier 或者  CRFEntityExtractor 来使用它
# CRFEntityExtractor vs MitieEntityExtractor

policies:
  - name: TEDPolicy
    epochs: 100
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy
